<div class="main-content">
    <div class="txt-heading">
        <h1>Shopping Cart</h1>
    </div>
    <br><br>
    
    <?php
    // Order validation message
    if(isset($_SESSION['order'])) {
        echo $_SESSION['order'];
        unset($_SESSION['order']);
    }
    
    // if session variable exists: if something is in the cart
    if(isset($_SESSION["cart"])){
        $total_quantity = 0;
        $total_price = 0;
    ?>	
    
        <!--Empty cart button-->
        <a href="index.php?road=emptyCart">  <button class="btnEmptyCart">Empty Cart</button></a>
        
        <!--Cart table-->
        <table class="tbl-full">
            <tr>
                <th></th>
                <th>Name</th>
                <th>Quantity</th>
                <th>Unit Price</th>
                <th>Price</th>
            </tr>
        
            <?php foreach ($data as $item):?>
            
            	<?php $item_price = $item["quantity"]*$item["article_price"]; ?>
                </tr>
            	    <td><?php if($item['article_image'] != "") { ?>
                        <img src="../public/img/collection/<?=$item['article_image']?>" width="100px">
                    <?php }
                    else {
                        echo "No Image added";
                        }?> 
                    </td>
            		<td><?= $item["article_name"] ?></td>
                    <td colspan="3">
                        <a href="index.php?road=downQty&id=<?= $item["article_id"] ?>">-</a>
            			<a><?=$item["quantity"]?></a>
                        <a href="index.php?road=upQty&id=<?= $item["article_id"] ?>">+</a>
            		</td>
            		<td><?= "$ ".$item["article_price"]?><input type='hidden' class='iprice' value=<?= $item["article_price"]?>></td>
            		<td><?= "$ ". number_format($item_price,2)?></td>
            		<td><a href="index.php?road=removeCart&id=<?= $item["article_id"] ?>" class="btnRemoveItem"><img src="icon-delete.png" alt="Remove Item" /></a></td>
        				
            		<?php
            		// add to total quantity and price
            		    $total_quantity += $item["quantity"];
            			$total_price += ($item["article_price"]*$item["quantity"]);
            		?>
        	    </tr>
        	    <?php endforeach?>
            <tr>
                <td colspan="2">Total:</td>
                <td class = "totalQty"><?= $total_quantity ?></td>
                <td colspan="2"><strong><?php echo "$ ".number_format($total_price, 2); ?></strong></td>
            </tr>
        </table>
        
        <!--validate order button-->
        <a href="index.php?road=getCommanderDetails">  <button class="btn-secondary" >Validate Order</button>
    
    
    <?php
    // if cart is empty
    } else {
    ?>
        <div class="no-records">Your Cart is Empty</div>
    <?php } ?>
</div>

<!--js for cart-->
<script src="../public/js/cart.js"></script>        





