<html>
<!--navbar social media start-->
<section class="social">
    <div class="container">
        <ul>
            <li>
                <a href="#" class="fa fa-facebook">Facebook</a>
            </li>
            <li>
                <a href="#" class="fa fa-twitter">Twitter</a>
            </li>
            <li>
                <a href="#" class="fa fa-instagram">Instagram</a>
            </li>
        </ul>
    </div>
</section>
<!--navbar social media end-->
    
<!--navbar footer start-->
<section class="footer">
    <div class="container">
        <p> ©2022 created by Yunita Bali Handmade Jewelry Team </p>
    </div>
</section>
<!--navbar footer end-->
</html>