<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Bali Earth Soul Jewelry</title>

    <!-- Link our CSS file -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="../public/css/style.css" rel="stylesheet" >
</head>
<body>
    
</body>

<!--menu items-->
<section class="navbar">
    <div class="container">
        <div class="logo">
            <img src="../public/upload/logobali.png" alt="shop logo" class="img-responsive"></img>
        </div>
        <div class="menu text-right">
            <ul>
                <li>
                    <a href="index.php?road=home">Home</a>
                </li>
                <li>
                    <a href="index.php?road=categories">Categories</a>
                </li>
                <li>
                    <a href="index.php?road=collections">Collections</a>
                </li>
                <li>
                    <a href="index.php?road=goContact">Contact</a>
                </li>
                <li class="nav-item">
                  <a href="index.php?road=cart"> Cart</a>
                </li>
                <!--if not logged-in show button for sign up/in -->
                <?php
                    if(!isset($_SESSION['auth'])) {
                ?>
                    <li class="nav-item">
                      <a href="index.php?road=auth"> Sign Up/In</a>
                    </li> 
                <!--if logged-in: show name of user-->
                <?php }else {?>
                    <li class="nav-item">
                      <a href="index.php?road=logout"> <?= $_SESSION['user'] ?>  Logout </a>
                    </li>    
                <?php } ?>
            </ul>
        </div>
        <div class="clearfix"></div>
    </div>
</section>
